### Get all users
GET http://localhost:3000/users

### Get a single user
GET http://localhost:3000/users/67efdc0bab286a4701c1253b

### Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Dan",
    "lastName": "Nat",
    "password": "thissimypasswords",
    "email": "natty@gmail.com"
}

### Update a user
PUT http://localhost:3000/users/67efdc0bab286a4701c1253b
Content-Type: application/json

{
    "firstName": "Ben",
    "lastName": "Dark",
    "password": "password1",
    "email": "darkbee@gmail.com"
}

### Delete a user
DELETE http://localhost:3000/users/67de4087f445b8d557646ca7

---

### **Task Requests**

### Get all tasks for a user
GET http://localhost:3000/tasks/67db68fd2f31d775f9062704

### Get a single task for a user
GET http://localhost:3000/tasks/67db68fd2f31d775f9062704/67dcba5265d31fd6e1aa181a

### Create a new task for a user
POST http://localhost:3000/tasks/67db68fd2f31d775f9062704
Content-Type: application/json

{
    "title": "tagalog",
    "description": "How to speak tagalog",
    "dueDate": "March 30, 2025",
    "progress": "working on it",
    "instructor": "mick manners",
    "subject": "filipino"
}

### Update a task for a user
PUT http://localhost:3000/tasks/67db68fd2f31d775f9062704/67e48806f18fd5b212727385
Content-Type: application/json

{
    "title": "Math Assignment",
    "description": "This assignment demonstrates my problem-solving skills in mathematics.",
    "dueDate": "March 22, 2025",
    "progress": "Finished it.",
    "instructor": "Dan Brown",
    "subject": "Mathematics"
}

### Delete a task for a user
DELETE http://localhost:3000/tasks/67db68fd2f31d775f9062704/67de4246f445b8d557646cab
